services:
  web-app:
    image: sulaymaan/fastapi-book-project
    expose:
      - 8000
    environment:
      - PORT=8000
    restart: unless-stopped  

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 80:80
    restart: always
    depends_on:
      - web-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
