name: CD for bookapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy application
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: SSH into machine 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.GCP_SERVER_IP }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.GCP_SSH_KEYS }}
          script: |
            cd ${{ vars.SERVICE_NAME }}
            docker compose down
            cd ../
            rm -rf ${{ vars.SERVICE_NAME }}
            git clone https://github.com/Sulai-maan/fastapi-book-project.git
            cd ${{ vars.SERVICE_NAME }}
            docker compose up --build -d
