name: CD for bookapi

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.HNG13_SERVICE_ACCOUNT }}
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev
      - name: Build and Push FastAPI Container
        run: |
          docker build -t ${{ vars.REGION }}-docker.pkg.dev/{{ vars.PROJECT_ID }}/cloud-run-source-deploy/${{ vars.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ vars.REGION }}-docker.pkg.dev/{{ vars.PROJECT_ID }}/cloud-run-source-deploy/${{ vars.SERVICE_NAME }}:${{ github.sha }}

      - name: Prepare new service ocnfig file
        run: |
          envsubst < service-yaml/${{ vars.SERVICE_NAME }}.yaml > processed-config.yaml
        env:
          SERVICE_NAME: ${{ vars.SERVICE_NAME }}
          SERVICE_NAMESPACE: ${{ vars.SERVICE_NAMESPACE }}
          REGION: ${{ vars.REGION }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          GITHUB_SHA: ${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE_NAME }}
          region: ${{ vars.REGION }}
          metadata: processed-config.yaml